---
# This file is copied from https://github.com/voxpupuli/modulesync_config
HOSTS:
  centos-7-x64:
    platform: el-7-x86_64
    hypervisor: docker
    image: centos:7
    docker_preserve_image: true
    docker_cmd: '["/usr/sbin/init"]'
    docker_image_commands:
      - 'yum install -y crontabs initscripts iproute openssl sysvinit-tools tar wget which ss'
      - 'yum install -y epel-release'
      - 'systemctl mask getty@tty1.service'
CONFIG:
  trace_limit: 200
masterless: true
